### ISSUE TITLE
Disable "Default Web" Context Menu

### ISSUE THREAD

**Issue by dubisdev** [kunkunsh/kunkun#76]
**Is your feature request related to a problem? Please describe.**
I think that something we can change in the app to make it feel more "native" is to disable the default context menu on right click.

**Describe the solution you'd like**
disbale it (maybe add custom context menu?)

**Describe alternatives you've considered**
NA

**Additional context**
![image](https://github.com/user-attachments/assets/be7faa97-4435-4be3-aed0-73ccb2838d43)

**Comment by HuakunShen** [comment]
Ideally, the production build shouldn’t include a this browser context menu or enable devtools by default. In extension development, however, devtools are essential for extension developers to access console logs conveniently.

Although implementing a proxy console window was considered to display logs within the app, it turned out to be simpler to let developers use the built-in browser devtools.

A potential solution could be to implement a custom context menu that includes a devtools option, but only if devtools are enabled in the settings. This way, the option is available to developers without exposing it in production by default.

**Comment by dubisdev** [comment]
Yes, for me having dev tools seems right, but I think we can leave them (they can be opened through `ctrl+shift+i`) and remove the context menu.

**Comment by HuakunShen** [comment]
![image](https://github.com/user-attachments/assets/abb9a01b-6faf-4050-bab4-e3ab1bcaf1c9)

I disabled the default web context menu, and moved them to the menu dropdown.
